<a href="https://colab.research.google.com/github/ashleyrennnnnn/Li-Ren/blob/main/Regression_model_part.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [301]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

In [302]:
data = pd.read_csv("pre-processed-data.csv", index_col = 0)
data=data.dropna()

In [303]:
select = data.info()
round(data.describe(), 2)

<class 'pandas.core.frame.DataFrame'>
Index: 9697 entries, GM0003 to BU19782002
Data columns (total 80 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   a_inw       9697 non-null   int64
 1   a_man       9697 non-null   int64
 2   a_vrouw     9697 non-null   int64
 3   a_00_14     9697 non-null   int64
 4   a_15_24     9697 non-null   int64
 5   a_25_44     9697 non-null   int64
 6   a_45_64     9697 non-null   int64
 7   a_65_oo     9697 non-null   int64
 8   a_ongeh     9697 non-null   int64
 9   a_gehuwd    9697 non-null   int64
 10  a_gesch     9697 non-null   int64
 11  a_verwed    9697 non-null   int64
 12  a_w_all     9697 non-null   int64
 13  a_nw_all    9697 non-null   int64
 14  a_marok     9697 non-null   int64
 15  a_antaru    9697 non-null   int64
 16  a_suri      9697 non-null   int64
 17  a_tur       9697 non-null   int64
 18  a_ov_nw     9697 non-null   int64
 19  a_geb       9697 non-null   int64
 20  p_geb       9697 non-null   int64
 21  a_ste       9697 non-null   int64
 22  p_ste       9697 non-null   int64
 23  a_hh        9697 non-null   int64
 24  a_1p_hh     9697 non-null   int64
 25  a_hh_z_k    9697 non-null   int64
 26  a_hh_m_k    9697 non-null   int64
 27  g_hhgro     9697 non-null   float64
 28  bev_dich    9697 non-null   float64
 29  a_woning    9697 non-null   int64
 30  g_woz       9697 non-null   float64
 31  p_1gezw     9697 non-null   float64
 32  p_mgezw     9697 non-null   float64
 33  p_bewndw    9697 non-null   float64
 34  p_leegsw    9697 non-null   float64
 35  p_koopw     9697 non-null   float64
 36  p_huurw     9697 non-null   float64
 37  p_wcorpw    9697 non-null   float64
 38  p_ov_hw     9697 non-null   float64
 39  p_e_o_w     9697 non-null   float64
 40  p_bjj2k     9697 non-null   float64
 41  p_bjo2k     9697 non-null   float64
 42  g_ele       9697 non-null   float64
 43  g_ele_vw    9697 non-null   float64
 44  g_ele_hu    9697 non-null   float64
 45  g_ele_ko    9697 non-null   float64
 46  g_gas       9697 non-null   float64
 47  g_gas_vw    9697 non-null   float64
 48  g_gas_hu    9697 non-null   float64
 49  g_gas_ko    9697 non-null   float64
 50  a_soz_wb    9697 non-null   float64
 51  a_soz_ao    9697 non-null   float64
 52  a_soz_ww    9697 non-null   float64
 53  a_soz_ow    9697 non-null   float64
 54  a_bedv      9697 non-null   int64
 55  a_bed_a     9697 non-null   float64
 56  a_bed_bf    9697 non-null   float64
 57  a_bed_gi    9697 non-null   float64
 58  a_bed_hj    9697 non-null   float64
 59  a_bed_kl    9697 non-null   float64
 60  a_bed_mn    9697 non-null   float64
 61  a_bed_ru    9697 non-null   float64
 62  a_pau       9697 non-null   int64
 63  a_bst_b     9697 non-null   int64
 64  a_bst_nb    9697 non-null   int64
 65  g_pau_hh    9697 non-null   float64
 66  g_pau_km    9697 non-null   float64
 67  a_m2w       9697 non-null   int64
 68  g_afs_hp    9697 non-null   float64
 69  g_afs_gs    9697 non-null   float64
 70  g_afs_kv    9697 non-null   float64
 71  g_afs_sc    9697 non-null   float64
 72  g_3km_sc    9697 non-null   float64
 73  a_opp_ha    9697 non-null   int64
 74  a_lan_ha    9697 non-null   int64
 75  a_wat_ha    9697 non-null   int64
 76  ste_mvs     9697 non-null   float64
 77  ste_oad     9697 non-null   float64
 78  sporting    9697 non-null   float64
 79  loneliness  9697 non-null   float64
dtypes: float64(44), int64(36)
memory usage: 6.0+ MB

,a_inw,a_man,a_vrouw,a_00_14,a_15_24,a_25_44,a_45_64,a_65_oo,a_ongeh,a_gehuwd,...,g_afs_kv,g_afs_sc,g_3km_sc,a_opp_ha,a_lan_ha,a_wat_ha,ste_mvs,ste_oad,sporting,loneliness
count,9697.00,9697.00,9697.00,9697.00,9697.00,9697.00,9697.00,9697.00,9697.00,9697.00,...,9697.00,9697.00,9697.00,9697.00,9697.00,9697.00,9697.00,9697.00,9697.00,9697.00
mean,4510.77,2238.28,2271.89,720.78,543.67,1067.63,1282.86,896.01,2120.17,1811.74,...,0.95,0.95,6.16,945.94,847.58,98.36,3.68,982.46,48.35,43.56
std,16552.24,8197.63,8356.14,2618.58,2144.93,5050.83,4280.01,2664.66,9373.27,5323.30,...,0.82,0.75,5.25,3346.07,2530.72,1382.41,1.35,919.98,6.92,5.06
min,115.00,55.00,55.00,0.00,0.00,5.00,20.00,5.00,30.00,45.00,...,0.10,0.20,0.00,4.00,4.00,0.00,1.00,8.00,19.80,30.30
25%,725.00,365.00,360.00,105.00,85.00,140.00,220.00,135.00,310.00,320.00,...,0.50,0.50,2.00,46.00,45.00,0.00,2.00,205.00,43.60,39.90
50%,1590.00,790.00,795.00,250.00,180.00,340.00,470.00,315.00,705.00,680.00,...,0.60,0.70,4.80,127.00,123.00,2.00,4.00,740.00,48.10,42.70
75%,3615.00,1790.00,1815.00,575.00,425.00,805.00,1040.00,750.00,1615.00,1510.00,...,1.10,1.10,9.10,751.00,717.00,13.00,5.00,1513.00,53.00,46.40
max,862965.00,427787.00,435178.00,125602.00,108487.00,311068.00,209828.00,107980.00,555066.00,210221.00,...,7.80,8.40,44.70,90787.00,52301.00,58873.00,5.00,8048.00,73.30,67.90

In [304]:
X = data.drop(["loneliness","sporting"],axis = 1)
y_loneliness = data["loneliness"]
y_sporting = data["sporting"]

## Regression model

Ridge，Lasso，LinearRegression

In [305]:
from sklearn.linear_model import Ridge,LinearRegression
from matplotlib.widgets import Lasso
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.pipeline import Pipeline
from typing import Union
from sklearn.model_selection import GridSearchCV,train_test_split
from typing import Union, List, Dict


X_sport_train, X_sport_test, y_sport_train, y_sport_test = train_test_split(
    X, y_sporting, random_state=100)
sport_data_dictionary = {
    "X_sport_train": X_sport_train,
    "X_sport_test": X_sport_test,
    "y_sport_train": y_sport_train,
    "y_sport_test": y_sport_test,
}

X_lone_train, X_lone_test, y_lone_train, y_lone_test = train_test_split(
    X, y_loneliness, random_state=100)
lone_data_dictionary = {
    "X_lone_train": X_lone_train,
    "X_lone_test": X_lone_test,
    "y_lone_train": y_lone_train,
    "y_lone_test": y_lone_test,
}
def get_classifier_and_scaler_1(
    classifier: Union[Ridge, Lasso, LinearRegression],
    scaler: Union[Union[StandardScaler, MinMaxScaler], None] = None,
) -> Pipeline:
    return Pipeline([("classifier", classifier)])

For Loneliness

In [306]:
from sklearn.metrics import mean_absolute_error,r2_score

def grid_search_and_test_1(model: Pipeline, params: Dict[str, List[float]]) -> None:
    """Prints the best parameters found for the model, and the score on the test data"""
    gsc = GridSearchCV(model, param_grid=params, n_jobs=4, error_score=0.0)
    gsc.fit(X_lone_train, y_lone_train)

    print("Best parameters found for Ridge:", gsc.best_params_)
    model.set_params(**gsc.best_params_)
    model.fit(X_lone_train, y_lone_train)

    pred = model.predict(X_lone_test)

    scores = {
        "Mean Absolute Error ": [mean_absolute_error(y_lone_test, pred)],
        "R2 score": [r2_score(y_lone_test, pred)],
    }
    score_df = pd.DataFrame(scores)

    return score_df

In [307]:
grid_search_and_test_1(
    get_classifier_and_scaler_1(Ridge(random_state=100)),{}
)

Best parameters found for Ridge: {}

   Mean Absolute Error   R2 score
0              1.694262  0.800596

In [308]:
from sklearn.metrics import mean_absolute_error,r2_score

def grid_search_and_test_1(model: Pipeline, params: Dict[str, List[float]]) -> None:
    """Prints the best parameters found for the model, and the score on the test data"""
    gsc = GridSearchCV(model, param_grid=params, n_jobs=4, error_score=0.0)
    gsc.fit(X_lone_train, y_lone_train)

    print("Best parameters found for Lasso:", gsc.best_params_)
    model.set_params(**gsc.best_params_)
    model.fit(X_lone_train, y_lone_train)

    pred = model.predict(X_lone_test)

    scores = {
        "Mean Absolute Error ": [mean_absolute_error(y_lone_test, pred)],
        "R2 score": [r2_score(y_lone_test, pred)],
    }
    score_df = pd.DataFrame(scores)

    return score_df

In [310]:
grid_search_and_test_1(
    get_classifier_and_scaler_1(Lasso()),{}
)

TypeError: ignored

In [311]:
from sklearn.metrics import mean_absolute_error,r2_score

def grid_search_and_test_1(model: Pipeline, params: Dict[str, List[float]]) -> None:
    """Prints the best parameters found for the model, and the score on the test data"""
    gsc = GridSearchCV(model, param_grid=params, n_jobs=4, error_score=0.0)
    gsc.fit(X_lone_train, y_lone_train)

    print("Best parameters found for LinearRegression:", gsc.best_params_)
    model.set_params(**gsc.best_params_)
    model.fit(X_lone_train, y_lone_train)

    pred = model.predict(X_lone_test)

    scores = {
        "Mean Absolute Error ": [mean_absolute_error(y_lone_test, pred)],
        "R2 score": [r2_score(y_lone_test, pred)],
    }
    score_df = pd.DataFrame(scores)

    return score_df

In [312]:
grid_search_and_test_1(
    get_classifier_and_scaler_1(LinearRegression()),{}
)

Best parameters found for LinearRegression: {}

   Mean Absolute Error   R2 score
0              1.694412  0.800505

For sport

In [313]:
from sklearn.metrics import mean_absolute_error,r2_score

def grid_search_and_test_1(model: Pipeline, params: Dict[str, List[float]]) -> None:
    """Prints the best parameters found for the model, and the score on the test data"""
    gsc = GridSearchCV(model, param_grid=params, n_jobs=4, error_score=0.0)
    gsc.fit(X_sport_train, y_sport_train)

    print("Best parameters found for Ridge:", gsc.best_params_)
    model.set_params(**gsc.best_params_)
    model.fit(X_sport_train, y_sport_train)

    pred = model.predict(X_sport_test)

    scores = {
        "Mean Absolute Error ": [mean_absolute_error(y_sport_test, pred)],
        "R2 score": [r2_score(y_sport_test, pred)],
    }
    score_df = pd.DataFrame(scores)

    return score_df

In [314]:
grid_search_and_test_1(
    get_classifier_and_scaler_1(Ridge(random_state=100)),{}
)

Best parameters found for Ridge: {}

   Mean Absolute Error   R2 score
0              3.267283  0.631361

In [315]:
from sklearn.metrics import mean_absolute_error,r2_score

def grid_search_and_test_1(model: Pipeline, params: Dict[str, List[float]]) -> None:
    """Prints the best parameters found for the model, and the score on the test data"""
    gsc = GridSearchCV(model, param_grid=params, n_jobs=4, error_score=0.0)
    gsc.fit(X_sport_train, y_sport_train)

    print("Best parameters found for Lasso:", gsc.best_params_)
    model.set_params(**gsc.best_params_)
    model.fit(X_sport_train, y_sport_train)

    pred = model.predict(X_sport_test)

    scores = {
        "Mean Absolute Error ": [mean_absolute_error(y_sport_test, pred)],
        "R2 score": [r2_score(y_sport_test, pred)],
    }
    score_df = pd.DataFrame(scores)

    return score_df

In [ ]:
grid_search_and_test_1(
    get_classifier_and_scaler_1(Lasso()),{}
)

In [316]:
from sklearn.metrics import mean_absolute_error,r2_score

def grid_search_and_test_1(model: Pipeline, params: Dict[str, List[float]]) -> None:
    """Prints the best parameters found for the model, and the score on the test data"""
    gsc = GridSearchCV(model, param_grid=params, n_jobs=4, error_score=0.0)
    gsc.fit(X_sport_train, y_sport_train)

    print("Best parameters found for LinearRegression:", gsc.best_params_)
    model.set_params(**gsc.best_params_)
    model.fit(X_sport_train, y_sport_train)

    pred = model.predict(X_sport_test)

    scores = {
        "Mean Absolute Error ": [mean_absolute_error(y_sport_test, pred)],
        "R2 score": [r2_score(y_sport_test, pred)],
    }
    score_df = pd.DataFrame(scores)

    return score_df

In [317]:
grid_search_and_test_1(
    get_classifier_and_scaler_1(LinearRegression()),{}
)

Best parameters found for LinearRegression: {}

   Mean Absolute Error   R2 score
0              3.267343  0.631227

DecisionTreeClassifier and RandomTreeClassifier

In [318]:
## List of categorical columns
catetgorical = [
    "a_man",
    "a_vrouw",
    "a_00_14",
    "a_15_24",
    "a_25_44",
    "a_45_64",
    "a_65_oo",
    "a_ongeh",
    "a_gehuwd",
    "a_gesch",
    "a_verwed",
    "a_marok",
    "a_antaru",
    "a_suri",
    "a_tur",
    "a_ov_nw",
    "a_1p_hh",
    "a_hh_z_k",
    "a_hh_m_k",
    "bev_dich",
    "p_wcorpw",
    "p_ov_hw",
    "p_e_o_w",
    "p_bjj2k",
    "p_bjo2k",
    "g_ele_ko",
    "g_ele_hu",
    "g_ele_vw",
    "a_soz_ow",
    "a_soz_ww",
    "a_soz_ao",
    "a_soz_wb",
    "a_bed_ru",
    "a_bed_mn",
    "a_bed_kl",
    "a_bed_hj",
    "a_bed_gi",
    "a_bed_bf",
    "a_bed_a",
    "a_m2w",
    "a_bst_nb",
    "a_bst_b",
    "g_3km_sc",
    "g_afs_sc",
    "g_afs_kv", 
    "g_afs_gs", 
    "g_afs_hp",
    "ste_mvs",
    "ste_oad",
]
# List of numerical columns
numerical = ["a_inw","a_w_all","a_nw_all","a_geb","p_geb","a_ste","p_ste","a_hh","g_hhgro","p_mgezw","p_1gezw","g_woz","a_woning","p_bewndw","p_leegsw","p_koopw","p_huurw","g_ele","p_stadsv","g_ gas_ ko","g_ gas_ hu","g_ gas_ vw","g_gas_2w","g_ gas_ hw","g_ gas_ tw","g_gas_ap","g_gas","g_ele","g_ink_pi","g_ink_po","a_inkont","g_gewsek","g_vernoo","g_wodief","a_bedv","g_pau_km","g_pau_hh","a_pau", "a_wat_ha", "a_lan_ha", "a_opp_ha","pst_dekp"]

In [319]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from typing import Union
from sklearn.compose import ColumnTransformer
from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder,LabelBinarizer

lab = preprocessing.LabelEncoder()
y_lone_transformed = lab.fit_transform(y_loneliness)
y_sport_transformed = lab.fit_transform(y_sporting)

X_lone_train, X_lone_test, y_lone_train, y_lone_test = train_test_split(
    X, y_lone_transformed, random_state=100)

X_sport_train, X_sport_test, y_sport_train, y_sport_test = train_test_split(
    X, y_sport_transformed, random_state=100)

def get_classifier_and_scaler_2(
    classifier: Union[DecisionTreeClassifier,RandomForestClassifier],
    scaler: Union[Union[StandardScaler, MinMaxScaler], None] = None,
) -> Pipeline:
    if scaler:
        ct = ColumnTransformer(
            [
                ("scaling", scaler, numerical),
                ("onehot", OneHotEncoder(handle_unknown="ignore"), catetgorical),
            ]
        )
        return Pipeline([("scaler", ct), ("classifier", classifier)])
    ct = ColumnTransformer(
        [("onehot", OneHotEncoder(handle_unknown="ignore"), catetgorical)]
    )
    return Pipeline([("scaler", ct), ("classifier", classifier)])

For loneliness

In [320]:
from sklearn.metrics import mean_absolute_error,r2_score

def grid_search_and_test_2(model: Pipeline, params: Dict[str, List[float]]) -> None:
    """Prints the best parameters found for the model, and the score on the test data"""
    gsc = GridSearchCV(model, param_grid=params, n_jobs=4, error_score=0.0)
    gsc.fit(X_lone_train, y_lone_train)

    print("Best parameters found for RandomForestClassifier :", gsc.best_params_)
    model.set_params(**gsc.best_params_)
    model.fit(X_lone_train, y_lone_train)

    pred = model.predict(X_lone_test)

    scores = {
        "Mean Absolute Error ": [mean_absolute_error(y_lone_test, pred)],
        "R2 score": [r2_score(y_lone_test, pred)],
    }
    score_df = pd.DataFrame(scores)

    return score_df

In [321]:
grid_search_and_test_2(
    get_classifier_and_scaler_2(RandomForestClassifier(random_state=100)),{}
)

Best parameters found for RandomForestClassifier : {}

   Mean Absolute Error   R2 score
0             30.535258  0.304213

In [322]:
from sklearn.metrics import mean_absolute_error,r2_score

def grid_search_and_test_2(model: Pipeline, params: Dict[str, List[float]]) -> None:
    """Prints the best parameters found for the model, and the score on the test data"""
    gsc = GridSearchCV(model, param_grid=params, n_jobs=4, error_score=0.0)
    gsc.fit(X_lone_train, y_lone_train)

    print("Best parameters found for DecisionTreeClassifier :", gsc.best_params_)
    model.set_params(**gsc.best_params_)
    model.fit(X_lone_train, y_lone_train)

    pred = model.predict(X_lone_test)

    scores = {
        "Mean Absolute Error ": [mean_absolute_error(y_lone_test, pred)],
        "R2 score": [r2_score(y_lone_test, pred)],
    }
    score_df = pd.DataFrame(scores)

    return score_df

In [323]:
grid_search_and_test_2(
    get_classifier_and_scaler_2(DecisionTreeClassifier(random_state=100)),{}
)

Best parameters found for DecisionTreeClassifier : {}

   Mean Absolute Error   R2 score
0                 33.76   0.21801

For sport

In [324]:
from sklearn.metrics import mean_absolute_error,r2_score

def grid_search_and_test_2(model: Pipeline, params: Dict[str, List[float]]) -> None:
    """Prints the best parameters found for the model, and the score on the test data"""
    gsc = GridSearchCV(model, param_grid=params, n_jobs=4, error_score=0.0)
    gsc.fit(X_sport_train, y_sport_train)

    print("Best parameters found for RandomForestClassifier :", gsc.best_params_)
    model.set_params(**gsc.best_params_)
    model.fit(X_sport_train, y_sport_train)

    pred = model.predict(X_sport_test)

    scores = {
        "Mean Absolute Error ": [mean_absolute_error(y_sport_test, pred)],
        "R2 score": [r2_score(y_sport_test, pred)],
    }
    score_df = pd.DataFrame(scores)

    return score_df

In [ ]:
grid_search_and_test_2(
    get_classifier_and_scaler_2(RandomForestClassifier(random_state=100)),{}
)

In [ ]:
from sklearn.metrics import mean_absolute_error,r2_score

def grid_search_and_test_2(model: Pipeline, params: Dict[str, List[float]]) -> None:
    """Prints the best parameters found for the model, and the score on the test data"""
    gsc = GridSearchCV(model, param_grid=params, n_jobs=4, error_score=0.0)
    gsc.fit(X_sport_train, y_sport_train)

    print("Best parameters found for DecisionTreeClassifier :", gsc.best_params_)
    model.set_params(**gsc.best_params_)
    model.fit(X_sport_train, y_sport_train)

    pred = model.predict(X_sport_test)

    scores = {
        "Mean Absolute Error ": [mean_absolute_error(y_sport_test, pred)],
        "R2 score": [r2_score(y_sport_test, pred)],
    }
    score_df = pd.DataFrame(scores)

    return score_df

In [ ]:
grid_search_and_test_2(
    get_classifier_and_scaler_2(DecisionTreeClassifier(random_state=100)),{}
)